---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example
spec:
  replicas: 1
  selector:
    matchLabels:
      component: example
  template:
    metadata:
      labels:
        component: example
        traffic-profile: delay-jitter-to-quad-one
    spec:
      containers:
      - name: ping-cloudflare
        image: nicolaka/netshoot
        command: [ ping, '1.1.1.1' ]
        resources:
          limits:
            memory: 200Mi
            cpu: 500m
        securityContext:
          capabilities:
            add:
              - NET_ADMIN

      - name: ping-google
        image: nicolaka/netshoot
        command: [ ping, '8.8.8.8' ]
        resources:
          limits:
            memory: 200Mi
            cpu: 500m
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
