---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example
spec:
  replicas: 1
  selector:
    matchLabels:
      component: example
  template:
    metadata:
      labels:
        component: example
        traffic-profile: delay-jitter-to-quad-one
    spec:
      containers:
      - name: busybox
        image: busybox:1.25
        command: [ ping, '1.1.1.1' ]
