---
apiVersion: k8s-netem.riasc.eu/v1
kind: TrafficProfile
metadata:
  name: profile-delay-jitter
spec:
  podSelector:
    matchLabels:
      traffic-profile: delay-jitter-to-quad-one

  type: Builtin
  parameters:
    netem:
      delay: 0.2 # seconds
      loss_ratio: 1 # in [0, 1]

  egress:
  - to:
    - ipBlock:
        cidr: 1.1.1.1/32
    - podSelector:
        matchLabels:
          component: example
  - ports:
    - port: 443
      protocol: TCP
    - port: 53
      protocol: UDP

  ingress:
  - ports:
    - port: 1234
  - from:
    - podSelector:
        matchLabels:
          traffic-profile: delay-jitter-to-quad-one
