---
apiVersion: k8s-netem.riasc.io/v1
kind: TrafficProfile
metadata:
  name: profile-delay-jitter
spec:
  podSelector:
    matchLabels:
      traffic-profile: delay-jitter-to-quad-one

  # egress:
  # - to:
  #   - ipBlock:
  #       cidr: 1.1.1.1/32
  #   - podSelector:
  #       matchLabels:
  #         component: test

  impairments:
    netem:
      delay: 1000
      jitter: 200

    rate:
      limit: 1000 # kb/s
