---
apiVersion: k8s-netem.riasc.eu/v1
kind: TrafficProfile
metadata:
  name: profile-flexe
spec:
  interfaceFilter: gre1

  podSelector:
    matchLabels:
      traffic-profile: profile-delay-jitter-flexe

  type: Flexe

  parameters:
    segments:
    - repeat: true

    profiles:
    - name: ethernet
      parameters:
        runTime: 30

        bandwidthUp: 100000
        bandwidthDown: 100000
        delay: 0.25
        delayVariation: 0.25
        delayCorrelation: 0
        loss: 0
        lossCorrelation: 0
        duplication: 0
        corruption: 0
        reorder: 0
        reorderCorrelation: 0

    - name: 3g
      parameters:
        runTime: 30

        bandwidthUp: 256
        bandwidthDown: 256
        delay: 200
        delayVariation: 50
        delayCorrelation: 0
        loss: 0.5
        lossCorrelation: 0
        duplication: 0.1
        corruption: 0.1
        reorder: 0.2
        reorderCorrelation: 0

    - name: gprs
      parameters:
        bandwidthUp: 60
        bandwidthDown: 60
        delay: 350
        delayVariation: 100
        delayCorrelation: 0
        loss: 0.5
        lossCorrelation: 0
        duplication: 0.1
        corruption: 0.1
        reorder: 0.2
        reorderCorrelation: 0

    - name: lte
      parameters:
        bandwidthUp: 5000
        bandwidthDown: 15000
        delay: 7.5
        delayVariation: 5
        delayCorrelation: 0
        loss: 0.025
        lossCorrelation: 0
        duplication: 0
        corruption: 0
        reorder: 0
        reorderCorrelation: 0

    - name: xdsl
      parameters:
        bandwidthUp: 2000
        bandwidthDown: 15000
        delay: 7.5
        delayVariation: 2.5
        delayCorrelation: 0
        loss: 0
        lossCorrelation: 0
        duplication: 0
        corruption: 0
        reorder: 0
        reorderCorrelation: 0

  egress:
  - to:
    - ipBlock:
        cidr: 1.1.1.1/32

    - podSelector:
        matchLabels:
          component: example

    ports:
    - port: 443
      protocol: TCP
    - port: 53
      protocol: UDP

  - to:
    - ipBlock:
        cidr: 8.8.8.8/32

  - ports:
    - port: 80
      protocol: tcp
