---
apiVersion: k8s-netem.riasc.eu/v1
kind: TrafficProfile
metadata:
  name: profile-delay-jitter-flexe
spec:
  podSelector:
    matchLabels:
      #traffic-profile: delay-jitter-to-quad-one
      traffic-profile: profile-delay-jitter-flexe

  type: Flexe

  parameters:
    segments:
    - repeat: True

    profiles:
    - name: ethernet
      parameters:
        bandwidthUp: 100000
        bandwidthDown: 100000
        delay: 0.25
        delayVariation: 0.25
        delayCorrelation: 0
        loss: 0
        lossCorrelation: 0
        duplication: 0
        corruption: 0
        reorder: 0
        reorderCorrelation: 0
        runTime: 30
    - name: 3g
      parameters:
        bandwidthUp: 256
        bandwidthDown: 256
        delay: 200
        delayVariation: 50
        delayCorrelation: 0
        loss: 0.5
        lossCorrelation: 0
        duplication: 0.1
        corruption: 0.1
        reorder: 0.2
        reorderCorrelation: 0
        runTime: 30

  egress:
  - to:
    - ipBlock:
        cidr: 1.1.1.1/32
    - podSelector:
        matchLabels:
          component: example
    ports:
    - port: 443
      protocol: TCP
    - port: 53
      protocol: UDP
    - port: 0
      protocol: ICMP
  - ports:
    - port: 80
      protocol: tcp

  ingress:
  - ports:
    - port: 1234
  - from:
    - podSelector:
        matchLabels:
          #traffic-profile: delay-jitter-to-quad-one
          traffic-profile: profile-delay-jitter-flexe
