---
apiVersion: k8s-netem.riasc.eu/v1
kind: TrafficProfile
metadata:
  name: profile-delay-jitter
spec:
  podSelector:
    matchLabels:
      traffic-profile: delay-jitter-to-quad-one

  type: Script
  parameters:
    netem:
      delay: 200000

  egress:
  - to:
    - ipBlock:
        cidr: 1.1.1.1/32
    - podSelector:
        matchLabels:
          component: example
    ports:
    - port: 443
      protocol: TCP
    - port: 53
      protocol: UDP
    - port: 0
      protocol: ICMP
  - ports:
    - port: 80
      protocol: tcp

  ingress:
  - ports:
    - port: 1234
  - from:
    - podSelector:
        matchLabels:
          traffic-profile: delay-jitter-to-quad-one
