---
apiVersion: k8s-netem.riasc.io/v1
kind: TrafficProfile
metadata:
  name: profile-delay-jitter
spec:
  podSelector:
    matchLabels:
      traffic-profile: delay-jitter-to-quad-one

  egress:
  - to:
    - ipBlock:
        cidr: 1.1.1.1/32
    - podSelector:
        matchLabels:
          component: test
    ports:
    - port: 443
      protocol: TCP
    - port: 53
      protocol: UDP
  - to:
    - ipBlock:
        cidr: 192.169.0.0/16
  ingress:
  - ports:
    - port: 1234
  - from:
    - podSelector:
        matchLabels:
          traffic-profile: delay-jitter-to-quad-one

  impairmentType: TC

  impairment:
    netem:
      loss_ratio: 5
      loss_correlation: 10
      duplication_ratio: 2
      delay: 1000
      jitter: 200
      delay_jitter_correlation: 10
      reorder_ratio: 10
      reorder_correlation: 5

    rate:
      limit: 100 # kbit/s
      buffer_length: 2000,
      latency: 20
