---
apiVersion: v1
kind: Namespace
metadata:
  name: riasc-system

---
kind: MutatingWebhookConfiguration
apiVersion: admissionregistration.k8s.io/v1beta1
metadata:
  name: mutating-webhook
webhooks:
  - name: webhook.webhook.svc
    rules:
      - operations: ["CREATE", "UPDATE"]
        apiGroups: ["*"]
        apiVersions: ["*"]
        resources: ["*"]
    clientConfig:
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNyRENDQVpRQ0NRRHRxMlhSYUtRQWd6QU5CZ2txaGtpRzl3MEJBUXNGQURBWE1SVXdFd1lEVlFRRERBeGgKWkcxcGMzTnBiMjVmWTJFd0lCY05NVGt3T0RJM01URXpPVEV4V2hnUE1qSTVNekEyTVRFeE1UTTVNVEZhTUJjeApGVEFUQmdOVkJBTU1ER0ZrYldsemMybHZibDlqWVRDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDCkFRb0NnZ0VCQUxDRzBDaTlXck1xOERZVWR4RjJtTFZuZlNBcTZPUWJjT3JTV3ZMQXl5R2FmZHUzYUszRWY5YkIKa0JrNnBUSmdScjIrV0YrN1IzaFJ6T3Myd1UvTytvS1pwR25OT2ZnOTYzZzVEOHJqVXFzSGxNanVKVzJFSlJ2dQpTSDhqKytIRG1lZGpKSXBscjkwcll3bFJYRDRFc1pVZjlZOXJXVVg5dGF5YTM2VlhzWFdleUU4SkxYSktTVXpnCkQ3Y1N3bno5TEtHRE9KUDNPV0RpYi9jazNsNGgyNDlvWHFHU3VmalhCcVIxbHdIRVJUNFFaUXhQVityOWhkb3gKTWdoNVAvYWtQS1I4cHJCbzR1QzR4TitnSEVhdEdIRndHalVicnVTMnhYVXQ2dS9PRlhrM0doSUFHaEZhMnFocApyYlRFbjJtYnl3RitQbjVkZ0E4cFljRkppS3dkRHZjQ0F3RUFBVEFOQmdrcWhraUc5dzBCQVFzRkFBT0NBUUVBClB5WEtsa3JyQWZSWG5IbjNnOFdMeXZ0Y0pBczgvaytJQlROdW9RL1R1SDF3a2pCZzRJV1RiTHdaRXZCU3NEbjIKYitzMUpJRjZ2cUJVaFBKWk84dVpGL2xYY3VkZG5VS1lnbjFXVEpTaG1jaXZjODREdFhyVmx3bVREYlhPdnpsegpPVHZGTFdaSGpyS1dwMmtFWnl5T0hyamg5Rk04T3RBTmZ4K2NtT09uR2taUFJwbFIrN3dqamw3ODdNb01JSjE2CndTcW4yV0JhTWlKOXZkNUV5Qk03TEM3dnV0MXMva2NoaG95bWdmR0MzeWFaYjRXdUFaeTc5azJuZVhHSnpQU0kKSm1QRGw4eUdFMy9sbU93LzdpT3ZiVEo0NXJhQWN4UUhnTlRTb2p2MzlRYTM1N0d6KzFEVkkzR04vTDZLdExKOQpTMmtnRTh0bDJsQlpVLytvQVpUZ2VRPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
      service:
        namespace: riasc-system
        name: k8s-netem-webhook
        path: /mutate

---
kind: Service
apiVersion: v1
metadata:
  name: k8s-netem-webhook
  namespace: riasc-system
spec:
  selector:
    app: webhook
  ports:
  - name: https
    protocol: TCP
    port: 443
    targetPort: 443

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: webhook
  namespace: riasc-system
  name: webhook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webhook
  template:
    metadata:
      labels:
        app: webhook
      name: webhook
    spec:
      containers:
      - name: webhook
        image: garethr/hook:latest
        imagePullPolicy: IfNotPresent
        args:
        - "--bind=0.0.0.0:443"
        - "--certfile=/certs/tls.crt"
        - "--keyfile=/certs/tls.key"
        - "app:app"
        volumeMounts:
          - readOnly: true
            mountPath: /certs
            name: webhook-certs
        readinessProbe:
          httpGet:
            path: /health
            scheme: HTTPS
            port: 443
          initialDelaySeconds: 3
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            scheme: HTTPS
            port: 443
          initialDelaySeconds: 3
          periodSeconds:
      volumes:
      - name: webhook-certs
        secret:
          secretName: webhook-certs
